services:
  ########################################
  ########### REVERSE-PROXY ##############
  ########################################
  traefik:
    image: ${TRAEFIK}
    command: --api.insecure=true --providers.docker=true #Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80" #The HTTP port
      - "8082:8080" #The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #so Traefik can listen to the Docker events
    networks:
      - onecx-app

  ########################################
  ############### DATABASE ###############
  ########################################
  postgresdb:
    image: ${POSTGRES}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresdb-init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.http.services.postgresdb.loadbalancer.server.port=5432"
      - "traefik.http.routers.postgresdb.rule=Host(`postgresdb`)"
    networks:
      - onecx-app

  pgadmin:
    image: ${PGADMIN}
    environment:
      PGADMIN_DEFAULT_EMAIL: capgemini@capgemini.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    volumes:
      - ./pgadmin-init/servers.json:/pgadmin4/servers.json
    depends_on:
      postgresdb:
        condition: service_healthy
    labels:
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin`)"
    networks:
      - onecx-app

  #############################################
  ################ Security ###################
  #############################################
  keycloak-app:
    image: ${KEYCLOAK}
    command:
      [
        "start-dev --import-realm",
      ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-init/realm-export.json:/opt/keycloak/data/import/realm.json
    labels:
      - "traefik.http.services.keycloak-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak-app.rule=Host(`keycloak-app`)"
    networks:
      - onecx-app

  #############################################
  ################ Mock ###################
  #############################################
  wiremock:
    image: ${WIREMOCK}
    volumes:
      - ./wiremock-init/:/home/wiremock/
    labels:
      - "traefik.http.services.wiremock.loadbalancer.server.port=8080"
      - "traefik.http.routers.wiremock.rule=Host(`wiremock`)"
    networks:
      - onecx-app

  ##############################################################
  ######### 1000kit apps #######################################
  ##############################################################
  tkit-portal-server:
    image: ${TKIT_PORTAL_SERVER}
    environment:
      QUARKUS_DATASOURCE_USERNAME: tkit-portal-server
      QUARKUS_DATASOURCE_PASSWORD: tkit-portal-server
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/tkit-portal-server?sslmode=disable"
      ONECX_MP_JWT_VERIFY_ISSUERS: http://keycloak-app/realms/OneCX
      ONECX_MP_JWT_VERIFY_PUBLICKEY_LOCATIONS: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs/
      TKIT_APM_YAML_MP_REST_URL: http://apm:8080/tkit-apm-rs/
      TENANT_RESOLVER_API_MP_REST_URL: http://tenant-resolver:8080/
      TKIT_DATAIMPORT_ENABLED: "true"
      TKIT_DATAIMPORT_CONFIGURATIONS_PORTAL_ENABLED: "true"
      TKIT_DATAIMPORT_CONFIGURATIONS_MFE_ENABLED: "true"
      # QUARKUS_LOG_LEVEL: DEBUG
      APM_REQUIRED: "true"
    depends_on:
      postgresdb:
        condition: service_healthy
    labels:
      - "traefik.http.services.tkit-portal-server.loadbalancer.server.port=8080"
      - "traefik.http.routers.tkit-portal-server.rule=Host(`tkit-portal-server`)"
    networks:
      - onecx-app

  data-mgmt:
    image: ${DATA_MGMT}
    environment:
      QUARKUS_DATASOURCE_USERNAME: datamgmt
      QUARKUS_DATASOURCE_PASSWORD: datamgmt
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/datamgmt?sslmode=disable"
      QUARKUS_TKIT_LOG_CONSOLE_JSON: "false"
    depends_on:
      postgresdb:
        condition: service_healthy
    labels:
      - "traefik.http.services.data-mgmt.loadbalancer.server.port=8080"
      - "traefik.http.routers.data-mgmt.rule=Host(`data-mgmt`)"
    networks:
      - onecx-app

  data-mgmt-ui:
    image: ${DATA_MGMT_UI}
    ports:
      - "9091:8080" 
    environment:
      DATA_MGMT_MP_REST_URL: http://data-mgmt:8080
      PORTAL_V1_MP_REST_URL: http://tkit-portal-server:8080/v1
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak-app:8080/realms/OneCX
      ORG_TKIT_PORTAL_MVC_MENU_DISABLEPERMISSIONS: "true"
      ORG_TKIT_PORTAL_MVC_DISABLEPERMISSIONS: "true"
    depends_on:
      postgresdb:
        condition: service_healthy
    labels:
      - "traefik.http.services.data-mgmt-ui.loadbalancer.server.port=8080"
      - "traefik.http.routers.data-mgmt-ui.rule=Host(`data-mgmt-ui`)"
    networks:
      - onecx-app

  apm:
    image: ${APM}
    environment:
      QUARKUS_DATASOURCE_USERNAME: apm
      QUARKUS_DATASOURCE_PASSWORD: apm
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/apm?sslmode=disable"
      MP_JWT_VERIFY_ISSUER: http://keycloak-app/realms/OneCX
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
    depends_on:
      postgresdb:
        condition: service_healthy
    labels:
      - "traefik.http.services.apm.loadbalancer.server.port=8080"
      - "traefik.http.routers.apm.rule=Host(`apm`)"
    networks:
      - onecx-app

  minio:
    image: ${MINIO}
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
      - 9001
    labels:
      - "test.property.minio.url=http://$${host:minio}:$${port:minio:9000}"
      - "test.property.minio.accesskey=my_access"
      - "test.property.minio.secretkey=my_secret"
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - onecx-app

volumes:
  postgres:

networks:
  onecx-app:
